export const ErrorCodes = {
  FILE: {
    TOO_LARGE: 'FILE_TOO_LARGE',
    INVALID_TYPE: 'INVALID_FILE_TYPE',
    CORRUPT: 'FILE_CORRUPT',
    EMPTY: 'FILE_EMPTY'
  },
  DOCUMENT: {
    PARSE_ERROR: 'DOCUMENT_PARSE_ERROR',
    INVALID_FORMAT: 'INVALID_FORMAT',
    TOO_LONG: 'DOCUMENT_TOO_LONG'
  },
  AI: {
    API_ERROR: 'AI_API_ERROR',
    RATE_LIMIT: 'AI_RATE_LIMIT',
    CONTEXT_TOO_LONG: 'CONTEXT_TOO_LONG'
  },
  AUTH: {
    INVALID_TOKEN: 'INVALID_TOKEN',
    EXPIRED: 'TOKEN_EXPIRED',
    RATE_LIMIT: 'RATE_LIMIT_EXCEEDED'
  }
} as const;