export const ErrorCodes = {
  FILE: {
    TOO_LARGE: "FILE_TOO_LARGE",
    INVALID_TYPE: "INVALID_FILE_TYPE",
    CORRUPT: "FILE_CORRUPT",
    EMPTY: "FILE_EMPTY",
    INVALID: "FILE_INVALID"
  },
  DOCUMENT: {
    PARSE_ERROR: "DOCUMENT_PARSE_ERROR",
    INVALID_FORMAT: "INVALID_FORMAT",
    TOO_LONG: "DOCUMENT_TOO_LONG",
    INVALID_STRUCTURE: "INVALID_STRUCTURE",
    INVALID_SECTION: "INVALID_SECTION",
    INVALID_CONTENT: "INVALID_CONTENT",
    INVALID_METADATA: "INVALID_METADATA"
  },
  OPTIONS: {
    INVALID: "INVALID_OPTIONS",
    INVALID_FORMAT: "INVALID_EXPORT_FORMAT",
    INVALID_AI_CONFIG: "INVALID_AI_CONFIG",
    INVALID_AI_MODEL: "INVALID_AI_MODEL"
  },
  AI: {
    API_ERROR: "AI_API_ERROR",
    RATE_LIMIT: "AI_RATE_LIMIT",
    TOKEN_LIMIT: "AI_TOKEN_LIMIT"
  }
} as const;

export type ErrorCode = typeof ErrorCodes[keyof typeof ErrorCodes][keyof typeof ErrorCodes[keyof typeof ErrorCodes]];